### ISSUE TITLE
请问一下，src/bean的接口ts类型都是自己一个个写上去的，还是脚本生成的？现实开发中，我们也要几百个接口也要一个个写？

### ISSUE THREAD

**Issue by YanRenqian** [cumt-robin/vue3-ts-blog-frontend#3]

**Comment by cumt-robin** [comment]
少的话，就是自己简单维护一下。如果太多，那最好基于一些工具或脚本生成一下。好像 swagger 就支持 json 文件，可以考虑基于 json + 脚本输出一下 d.ts。或者可能市面上有一些类似的工具，我没太找这方面资源。
