### ISSUE TITLE
关于本地启动，调用openai的接口一直报timeout的问题

### ISSUE THREAD

**Issue by CharlesGC** [cumt-robin/vue3-ts-blog-frontend#4]
感谢大佬写了chatGPT的例子，但是我在本地启动项目后，调用api.openai.com的接口就一直报timeout，我本地也试过开启全局代理，但是不管用，还望大佬指点一二

**Comment by cumt-robin** [comment]
不好意思，太久没看 issue，目前还是考虑全匿名ip访问这方面
